# Generated by Django 5.0.6 on 2024-05-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='foodimage')),
                ('potion', models.CharField(choices=[('Quater', 'Quater'), ('Half', 'Half'), ('Full', 'Full')], max_length=255)),
                ('diet', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Egg', 'Egg')], max_length=20)),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Products.foodcategory')),
            ],
        ),
    ]
