# Generated by Django 5.0.6 on 2024-05-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
