# Generated by Django 5.0.6 on 2024-05-30 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='potion',
            field=models.CharField(choices=[('Quarter', 'Quarter'), ('Half', 'Half'), ('Full', 'Full')], max_length=255),
        ),
    ]
