# Generated by Django 5.0.6 on 2024-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_menu_create_date_alter_menu_potion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_number', models.IntegerField()),
                ('Number_of_Seats', models.IntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='diet',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Egg', 'Egg')], max_length=20),
        ),
    ]
