# Generated by Django 5.0.6 on 2024-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_order_checkout_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='take_order',
            field=models.BooleanField(default=False),
        ),
    ]
