# Generated by Django 5.0.6 on 2024-06-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_order_completion_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Kitchen', 'In Kitchen'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Order Ready', 'Order Ready'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
