# Generated by Django 5.0.6 on 2024-06-01 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_orderitem_completion_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
