# Generated by Django 5.0.6 on 2024-06-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_checkout_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=20)),
                ('tax_percentage', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='price_Before_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='tax',
            field=models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], default='Inclusive', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='tax_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.tax'),
        ),
    ]
