# Generated by Django 5.0.6 on 2024-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_tax_menu_price_before_tax_menu_tax_menu_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='tax',
            field=models.CharField(choices=[('Inclusive', 'Inclusive'), ('Exclusive', 'Exclusive')], max_length=20),
        ),
    ]
