# Generated by Django 5.0.6 on 2024-06-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_menu_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
